omniauth:
  facebook:
      key:
      secret:
  twitter:
      key:
      secret:
  google:
      key:
      secret:
  windowslive:
      key:
      secret:
  linkedin:
      key:
      secret:

exceptional:
  api_key:
  
google_analytics:
  account_id:
  
sharethis:
  publisher_id:

s3:
  development:
    access_key_id:
    secret_access_key:
    bucket:
  production:
    access_key_id:
    secret_access_key:
    bucket:

rollbar:
  server_side_access_token:

redis:
  development:
    endpoint:
    password:
  production:
    endpoint:
    password:
