
common: &default_settings
  license_key: '3d55356357429ef2e20bc676a98e71e506e98236'
  app_name: 'DreamSIS_Production'
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: true
  capture_params: false

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
