development:
  host: ucswseval1.cac.washington.edu
  tenant_options:
    uwdp:
      cert: uwdp.crt
      key: uwdp.key
      ca_file: uwca.pem
      act_as_user: dreamsis
production:
  host: ws.admin.washington.edu
  tenant_options:
    uwdp:
      cert: uwdp.crt
      key: uwdp.key
      ca_file: uwca.pem
      act_as_user: dreamsis
