development:
    host: wseval.s.uw.edu
    cert: uwdp.crt
    key: uwdp.key
    ca_file: uwca.pem
    act_as_user: dreamsis

production:
    # host: ws.admin.washington.edu
    host: wseval.s.uw.edu
    cert: uwdp.crt
    key: uwdp.key
    ca_file: uwca.pem
    act_as_user: dreamsis
