development:
    host: ucswseval1.cac.washington.edu
    cert: uwdp.crt
    key: uwdp.key
    ca_file: uwca.pem
    act_as_user: dreamsis

production:
    host: ucswseval1.cac.washington.edu
    cert: uwdp.crt
    key: uwdp.key
    ca_file: uwca.pem
    act_as_user: dreamsis
